import math
print(math.exp(3))
print(math.log10(10))
print(math.pow(2,4))
print(math.sqrt(81))
print(math.ceil(3.14))
print(math.factorial(5))
print(math.acos(0))
print(math.sin(0))
x=math.degrees(90)
y=math.radians(90)
print(x)
print(y)
print(math.sin(x))
print(math.sin(y))